<?php

declare(strict_types=1);

namespace App\Http\Controllers\Webhook;

use App\Http\Controllers\Controller;
use App\Models\Member;
use App\Services\WhatsAppReminderConfirmationService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Receives inbound WhatsApp webhooks from UltraMsg.
 */
class UltraMsgWebhookController extends Controller
{
    public function handle(Request $request, WhatsAppReminderConfirmationService $confirmation): JsonResponse
    {
        $payload = $request->all();

        if ($this->isFromSelf($payload)) {
            return response()->json(['success' => true, 'ignored' => 'outgoing']);
        }

        $phone = $this->extractPhone($payload);
        $messageText = $this->extractMessageText($payload);

        if (! $phone || ! $messageText) {
            return response()->json(['success' => true, 'ignored' => 'missing_phone_or_text']);
        }

        $reply = $confirmation->parseReply($messageText);
        if (! $reply) {
            return response()->json(['success' => true, 'ignored' => 'not_yes_no']);
        }

        $member = Member::query()
            ->where('whatsapp_phone', $phone)
            ->where('whatsapp_confirmation_status', 'pending')
            ->orderByDesc('whatsapp_confirmation_requested_at')
            ->first();

        if (! $member) {
            return response()->json(['success' => true, 'ignored' => 'no_pending_member']);
        }

        if ($reply === 'yes') {
            $member->forceFill([
                'whatsapp_reminder_enabled' => true,
                'whatsapp_confirmation_status' => 'confirmed',
                'whatsapp_confirmation_responded_at' => now(),
            ])->save();

            $confirmation->sendConfirmedNotice($member);

            return response()->json(['success' => true, 'action' => 'confirmed']);
        }

        $member->forceFill([
            'whatsapp_reminder_enabled' => false,
            'whatsapp_confirmation_status' => 'rejected',
            'whatsapp_confirmation_responded_at' => now(),
            'whatsapp_last_sent_date' => null,
        ])->save();

        $confirmation->sendRejectedNotice($member);

        return response()->json(['success' => true, 'action' => 'rejected']);
    }

    /**
     * Incoming webhook can contain nested fields; extract sender phone.
     */
    private function extractPhone(array $payload): ?string
    {
        $candidates = [
            data_get($payload, 'from'),
            data_get($payload, 'data.from'),
            data_get($payload, 'sender'),
            data_get($payload, 'data.sender'),
            data_get($payload, 'chatId'),
            data_get($payload, 'data.chatId'),
            data_get($payload, 'remoteJid'),
            data_get($payload, 'data.remoteJid'),
        ];

        foreach ($candidates as $raw) {
            if (! is_string($raw) || trim($raw) === '') {
                continue;
            }

            $digits = preg_replace('/\D/', '', $raw);
            $normalized = normalizeUkWhatsAppPhone($digits);
            if ($normalized) {
                return $normalized;
            }
        }

        return null;
    }

    /**
     * Extract inbound message body text from common UltraMsg payload keys.
     */
    private function extractMessageText(array $payload): ?string
    {
        $candidates = [
            data_get($payload, 'body'),
            data_get($payload, 'data.body'),
            data_get($payload, 'message'),
            data_get($payload, 'data.message'),
            data_get($payload, 'text'),
            data_get($payload, 'data.text'),
        ];

        foreach ($candidates as $raw) {
            if (is_string($raw) && trim($raw) !== '') {
                return trim($raw);
            }
        }

        return null;
    }

    /**
     * Ignore webhook events generated by our own outgoing messages.
     */
    private function isFromSelf(array $payload): bool
    {
        $flags = [
            data_get($payload, 'fromMe'),
            data_get($payload, 'data.fromMe'),
            data_get($payload, 'sentByMe'),
            data_get($payload, 'data.sentByMe'),
        ];

        foreach ($flags as $flag) {
            if (is_bool($flag) && $flag === true) {
                return true;
            }
            if (is_string($flag) && in_array(strtolower($flag), ['true', '1', 'yes'], true)) {
                return true;
            }
            if (is_int($flag) && $flag === 1) {
                return true;
            }
        }

        // If webhook type is clearly outgoing, skip it.
        $type = data_get($payload, 'type') ?? data_get($payload, 'event_type') ?? data_get($payload, 'data.type');
        if (is_string($type) && str_contains(strtolower($type), 'out')) {
            return true;
        }

        return false;
    }
}
